#!/usr/bin/env bash

#
# Called with no arguments. Will prompt for confirmation.
# Installs latest versions of all dependencies and updates their version numbers in
# package.json. Will then commit package.json if there are any changes.
#

set -e # always immediately exit upon error

scripts_dir="`dirname $0`"

"$scripts_dir/require-clean-working-tree"

read -p "Do you want to update all depedencies and commit changes in package.json (y/N): " yn

if [[ "$yn" != "y" ]]
then
  exit
fi

npm update # will modify package.json, but won't commit

if "$scripts_dir/require-clean-working-tree" package.json
then
  echo 'No dependencies to update'
else
  git add package.json
  git commit -m 'update dependencies'
  echo 'Updated dependencies'
fi
